name: The Game
favicon: null
layout_spectrum: 0.26225492381490767
typography_spectrum: 0.3988877618685365
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8074601169209927
  lightness: 0.6330204410478473
  saturation: 0.23265150375664234
  rhythmicContrast: 0.4037932406645268
purpose: []
