name: The Game
favicon: null
layout_spectrum: 0.32491
typography_spectrum: 0.40135
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74925626-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00154e'
    - '#2a5d96'
    - '#ae2a99'
    - '#9b8fa9'
    - '#edafb5'
  brandStrength: 0.75
  lightness: 0.6330204410478473
  saturation: 0.25
  rhythmicContrast: 0.4037932406645268
purpose: []
